# -*- coding: utf-8 -*-
"""LLM-Wiki adapter — compiler-pattern knowledge base.

Implements the LLM-Wiki architecture (AOT retrieval) as described
in https://gist.github.com/rohitg00/2067ab416f7bbe447c1977edaaa681e2

Three-layer model:

1. **Raw layer** (``raw_dir``) — immutable source documents stored
   as files. This is the "source of truth" — the trust root.
2. **Wiki/compiled layer** (``compiled_dir``) — structured Markdown
   wiki pages generated by an LLM compilation pass. Each page covers
   a concept/entity extracted from the raw sources, with
   cross-references and metadata. This is the retrieval target.
3. **Index** — a keyword/embedding index over the compiled pages
   for fast retrieval.

The compilation pipeline:

    Raw document → chunk → LLM extract entities/summaries
    → generate wiki pages → cross-link → write to compiled_dir
    → build index

Retrieval hits the compiled layer (not raw), so it's fast (ms-level
vs minute-level for full-text search).

This is a **skeleton implementation** — the LLM compilation step
and the embedding index are stubbed with simple keyword matching.
Production use requires wiring a real LLM and embedding model.
"""
from __future__ import annotations

import json
import os
import re
import time
from datetime import datetime
from typing import Any

from ._base import (
    KnowledgeChunk,
    KnowledgeQuery,
    KnowledgeResult,
    KnowledgeSource,
)
from ._adapter import KnowledgeAdapter
from ._registry import _chunk_in_scope

# Module-level compiled pattern for whitelist validation.
# Only alphanumeric, underscore, and hyphen are allowed.
# ``\Z`` (not ``$``) is used because ``$`` also matches just
# before a trailing newline, which would let ``"evil\n"`` through.
_SAFE_PATH_COMPONENT = re.compile(r"^[a-zA-Z0-9_-]+\Z")


class LlmWikiAdapter(KnowledgeAdapter):
    """LLM-Wiki compiler-pattern knowledge base adapter.

    Stores raw sources as JSON files and compiled wiki pages as
    Markdown files. Uses simple keyword matching for retrieval
    (to be replaced with embedding-based search in production).

    Args:
        config (`KnowledgeBaseConfig`):
            Configuration with ``raw_dir`` and ``compiled_dir``
            paths set.
    """

    @classmethod
    def backend_name(cls) -> str:
        """Return the backend name.

        Returns:
            `str`: ``"llm_wiki"``
        """
        return "llm_wiki"

    async def initialize(self) -> None:
        """Create directories and load the index."""
        os.makedirs(self.config.raw_dir, exist_ok=True)
        os.makedirs(self.config.compiled_dir, exist_ok=True)
        self._index: dict[str, dict[str, Any]] = {}
        self._load_index()
        self._initialized = True

    def _load_index(self) -> None:
        """Load the compiled page index from disk.

        In scoped_layout mode, walks all tenant/kb index dirs and
        loads manifest.json files. In flat mode, loads _index.json.
        """
        self._index = {}
        if self._scoped_layout_enabled():
            # Walk tenant/kb dirs and load manifest.json
            tenants_root = os.path.join(
                self.config.raw_dir,
                "tenants",
            )
            if not os.path.exists(tenants_root):
                return
            for tenant_name in os.listdir(tenants_root):
                kbs_root = os.path.join(tenants_root, tenant_name, "kbs")
                if not os.path.isdir(kbs_root):
                    continue
                for kb_name in os.listdir(kbs_root):
                    index_dir = os.path.join(kbs_root, kb_name, "index")
                    manifest_path = os.path.join(index_dir, "manifest.json")
                    if os.path.exists(manifest_path):
                        with open(manifest_path, encoding="utf-8") as f:
                            scoped = json.load(f)
                        self._index.update(scoped)
        else:
            index_path = os.path.join(
                self.config.compiled_dir,
                "_index.json",
            )
            if os.path.exists(index_path):
                with open(index_path, "r", encoding="utf-8") as f:
                    self._index = json.load(f)

    def _save_index(self) -> None:
        """Persist the index to disk."""
        index_path = os.path.join(
            self.config.compiled_dir,
            "_index.json",
        )
        with open(index_path, "w", encoding="utf-8") as f:
            json.dump(self._index, f, ensure_ascii=False, indent=2)

    def _scoped_layout_enabled(self) -> bool:
        """Whether to use tenant/KB physical directories."""
        return bool(self.config.extra.get("scoped_layout"))

    @staticmethod
    def _validate_path_component(label: str, value: str) -> None:
        """Reject path traversal and unsafe characters in tenant/kb ids.

        Uses a whitelist (allow-list) approach: only alphanumeric
        characters, underscores, and hyphens are permitted. This
        prevents path traversal via ``..``, null bytes, URL encoding,
        Unicode normalization, control characters, and other bypass
        techniques that a blacklist would miss.

        Args:
            label (`str`): Field name for the error message.
            value (`str`): The value to check.

        Raises:
            `ValueError`: If the value is empty or contains
                characters outside ``[a-zA-Z0-9_-]``.
        """
        if not value or not _SAFE_PATH_COMPONENT.match(value):
            raise ValueError(
                f"Unsafe path component in {label}: {value!r} "
                f"(only [a-zA-Z0-9_-] allowed)",
            )

    def _kb_root(self, tenant_id: str, kb_id: str) -> str:
        """Return the physical root for a tenant/KB.

        Args:
            tenant_id (`str`): Tenant identifier (validated).
            kb_id (`str`): KB identifier (validated).

        Returns:
            `str`: The physical root path.

        Raises:
            `ValueError`: If tenant_id or kb_id contains path
                traversal characters.
        """
        self._validate_path_component("tenant_id", tenant_id)
        self._validate_path_component("kb_id", kb_id)
        return os.path.join(
            self.config.raw_dir,
            "tenants",
            tenant_id,
            "kbs",
            kb_id,
        )

    def _raw_dir_for(self, tenant_id: str, kb_id: str) -> str:
        if not self._scoped_layout_enabled():
            return self.config.raw_dir
        return os.path.join(self._kb_root(tenant_id, kb_id), "raw")

    def _compiled_dir_for(self, tenant_id: str, kb_id: str) -> str:
        if not self._scoped_layout_enabled():
            return self.config.compiled_dir
        return os.path.join(self._kb_root(tenant_id, kb_id), "wiki")

    def _index_dir_for(self, tenant_id: str, kb_id: str) -> str:
        if not self._scoped_layout_enabled():
            return self.config.compiled_dir
        return os.path.join(self._kb_root(tenant_id, kb_id), "index")

    def _audit_dir_for(self, tenant_id: str, kb_id: str) -> str:
        """Return the audit directory for a tenant/KB."""
        if not self._scoped_layout_enabled():
            return os.path.join(self.config.raw_dir, "audit")
        return os.path.join(self._kb_root(tenant_id, kb_id), "audit")

    def _write_audit(
        self,
        action: str,
        tenant_id: str,
        kb_id: str,
        **extra: Any,
    ) -> None:
        """Append an audit entry to knowledge-audit.jsonl.

        Args:
            action (`str`): The action (ingest/compile/retrieve/delete).
            tenant_id (`str`): Tenant scope.
            kb_id (`str`): KB scope.
            **extra: Additional fields for the audit entry.
        """
        audit_dir = self._audit_dir_for(tenant_id, kb_id)
        os.makedirs(audit_dir, exist_ok=True)
        audit_path = os.path.join(audit_dir, "knowledge-audit.jsonl")
        entry = {
            "timestamp": datetime.now().isoformat(),
            "action": action,
            "tenant_id": tenant_id,
            "kb_id": kb_id,
            **extra,
        }
        with open(audit_path, "a", encoding="utf-8") as f:
            f.write(json.dumps(entry, ensure_ascii=False) + "\n")

    def _redact_secrets(self, content: str) -> str:
        """Redact common secret patterns from content before storing.

        Args:
            content (`str`): Raw content.

        Returns:
            `str`: Content with secrets replaced by ``[REDACTED_*]``.
        """
        redacted = content
        # API keys: sk- followed by 20+ alphanumeric chars
        redacted = re.sub(
            r"sk-[a-zA-Z0-9]{20,}",
            "[REDACTED_API_KEY]",
            redacted,
        )
        # Bearer tokens
        redacted = re.sub(
            r"Bearer\s+[a-zA-Z0-9\-._~+/]+=*",
            "Bearer [REDACTED_TOKEN]",
            redacted,
        )
        # Private key blocks
        redacted = re.sub(
            r"-----BEGIN [A-Z ]*PRIVATE KEY-----"
            r".*?-----END [A-Z ]*PRIVATE KEY-----",
            "[REDACTED_PRIVATE_KEY]",
            redacted,
            flags=re.DOTALL,
        )
        return redacted

    async def ingest(
        self,
        source_id: str,
        content: str,
        title: str = "",
        source_type: str = "text",
        metadata: dict[str, Any] | None = None,
    ) -> KnowledgeSource:
        """Store a raw source document as a JSON file.

        Args:
            source_id (`str`):
                Unique source identifier.
            content (`str`):
                Raw content.
            title (`str`):
                Source title.
            source_type (`str`):
                Source type.
            metadata (`dict | None`):
                Extra metadata.

        Returns:
            `KnowledgeSource`: The stored source record.
        """
        source_metadata = {
            "tenant_id": "default",
            "kb_id": "default",
        }
        source_metadata.update(metadata or {})
        # Redact secrets before storing
        redacted_content = self._redact_secrets(content)
        source = KnowledgeSource(
            source_id=source_id,
            title=title or source_id,
            content=redacted_content,
            source_type=source_type,
            metadata=source_metadata,
            created_at=datetime.now().isoformat(),
        )

        raw_dir = self._raw_dir_for(
            source.metadata.get("tenant_id", "default"),
            source.metadata.get("kb_id", "default"),
        )
        os.makedirs(raw_dir, exist_ok=True)
        path = os.path.join(
            raw_dir,
            f"{source_id}.json",
        )
        with open(path, "w", encoding="utf-8") as f:
            json.dump(
                {
                    "source_id": source.source_id,
                    "title": source.title,
                    "content": source.content,
                    "source_type": source.source_type,
                    "metadata": source.metadata,
                    "created_at": source.created_at,
                },
                f,
                ensure_ascii=False,
                indent=2,
            )

        self._write_audit(
            "ingest",
            source.metadata.get("tenant_id", "default"),
            source.metadata.get("kb_id", "default"),
            source_id=source_id,
            title=source.title,
        )

        if self.config.auto_compile:
            await self.compile()

        return source

    async def compile(self) -> int:
        """Compile raw sources into structured wiki pages.

        For each raw source that hasn't been compiled yet:
        1. Split content into sections (by heading or paragraphs).
        2. Extract keywords (simple frequency-based; production
           should use LLM for entity extraction).
        3. Generate a wiki page per section as Markdown.
        4. Update the keyword index.

        Returns:
            `int`: Number of chunks (wiki pages) produced.
        """
        if not self._initialized:
            await self.initialize()

        # Track compiled source_ids scoped by (tenant_id, kb_id, source_id)
        # so the same source_id in different tenants doesn't get skipped.
        compiled_ids = {
            (
                entry.get("metadata", {}).get("tenant_id", "default"),
                entry.get("metadata", {}).get("kb_id", "default"),
                entry.get("source_id"),
            )
            for entry in self._index.values()
        }

        chunk_count = 0
        source_paths: list[str] = []
        if self._scoped_layout_enabled():
            for root, _dirs, files in os.walk(self.config.raw_dir):
                if os.path.basename(root) != "raw":
                    continue
                for filename in files:
                    if filename.endswith(".json"):
                        source_paths.append(os.path.join(root, filename))
        else:
            for filename in os.listdir(self.config.raw_dir):
                if filename.endswith(".json"):
                    source_paths.append(
                        os.path.join(self.config.raw_dir, filename),
                    )

        for source_path in source_paths:
            with open(source_path, "r", encoding="utf-8") as f:
                source_data = json.load(f)

            source_id = source_data["source_id"]
            source_meta = source_data.get("metadata", {})
            source_tenant = source_meta.get("tenant_id", "default")
            source_kb = source_meta.get("kb_id", "default")
            if (source_tenant, source_kb, source_id) in compiled_ids:
                continue

            sections = self._split_sections(
                source_data["content"],
                source_data.get("title", source_id),
            )

            for i, (heading, body) in enumerate(sections):
                # Include tenant/kb in chunk_id to avoid collisions
                # when the same source_id exists in different tenants.
                chunk_id = (
                    f"{source_tenant}__{source_kb}__{source_id}__{i}"
                    if self._scoped_layout_enabled()
                    else f"{source_id}__{i}"
                )
                keywords = self._extract_keywords(body)

                metadata = source_data.get("metadata", {})
                compiled_dir = self._compiled_dir_for(
                    metadata.get("tenant_id", "default"),
                    metadata.get("kb_id", "default"),
                )
                os.makedirs(compiled_dir, exist_ok=True)
                wiki_path = os.path.join(
                    compiled_dir,
                    f"{chunk_id}.md",
                )
                # YAML frontmatter with tenant/kb/source metadata
                frontmatter = (
                    f"---\n"
                    f"tenant_id: "
                    f"{metadata.get('tenant_id', 'default')}\n"
                    f"kb_id: "
                    f"{metadata.get('kb_id', 'default')}\n"
                    f"source_id: {source_id}\n"
                    f"section: {i + 1}\n"
                    f"compiled_at: "
                    f"{datetime.now().isoformat()}\n"
                    f"---\n\n"
                )
                wiki_content = (
                    f"{frontmatter}"
                    f"# {heading}\n\n"
                    f"**Source**: "
                    f"{source_data.get('title', source_id)}\n"
                    f"**Section**: {i + 1}\n\n"
                    f"{body}\n"
                )
                with open(wiki_path, "w", encoding="utf-8") as f:
                    f.write(wiki_content)

                self._index[chunk_id] = {
                    "source_id": source_id,
                    "title": heading,
                    "keywords": keywords,
                    "file": f"{chunk_id}.md",
                    "metadata": source_data.get("metadata", {}),
                }
                chunk_count += 1

        self._save_index()
        if self._scoped_layout_enabled():
            written_dirs: set[str] = set()
            for entry in self._index.values():
                metadata = entry.get("metadata", {})
                tid = metadata.get("tenant_id", "default")
                kid = metadata.get("kb_id", "default")
                index_dir = self._index_dir_for(tid, kid)
                if index_dir in written_dirs:
                    continue
                written_dirs.add(index_dir)
                os.makedirs(index_dir, exist_ok=True)
                scoped = {
                    cid: item
                    for cid, item in self._index.items()
                    if item.get("metadata", {}).get("tenant_id", "default")
                    == tid
                    and item.get("metadata", {}).get("kb_id", "default") == kid
                }
                # Write manifest.json (the per-KB index manifest)
                manifest_path = os.path.join(index_dir, "manifest.json")
                with open(manifest_path, "w", encoding="utf-8") as f:
                    json.dump(scoped, f, ensure_ascii=False, indent=2)
                # Also write _index.json for backward compat
                index_path = os.path.join(index_dir, "_index.json")
                with open(index_path, "w", encoding="utf-8") as f:
                    json.dump(scoped, f, ensure_ascii=False, indent=2)
                # Audit the compile
                self._write_audit(
                    "compile",
                    tid,
                    kid,
                    chunks_produced=len(scoped),
                )
        return chunk_count

    def _split_sections(
        self,
        content: str,
        fallback_title: str,
    ) -> list[tuple[str, str]]:
        """Split content into (heading, body) sections.

        Splits by Markdown headings (``#``) or by double newlines
        as a fallback.

        Args:
            content (`str`):
                The content to split.
            fallback_title (`str`):
                Title for the first section if no heading found.

        Returns:
            `list[tuple[str, str]]`: (heading, body) pairs.
        """
        lines = content.split("\n")
        sections: list[tuple[str, str]] = []
        current_heading = fallback_title
        current_body: list[str] = []

        for line in lines:
            if line.strip().startswith("#"):
                if current_body:
                    sections.append(
                        (
                            current_heading,
                            "\n".join(current_body).strip(),
                        ),
                    )
                current_heading = line.strip().lstrip("#").strip()
                current_body = []
            else:
                current_body.append(line)

        if current_body:
            body = "\n".join(current_body).strip()
            if body:
                sections.append((current_heading, body))

        if not sections:
            sections.append((fallback_title, content))

        return sections

    def _extract_keywords(self, text: str) -> list[str]:
        """Extract keywords from text (simple frequency-based).

        Production should use LLM-based entity extraction or
        a proper NLP library.

        Args:
            text (`str`):
                The text to extract keywords from.

        Returns:
            `list[str]`: Top keywords.
        """
        words = re.findall(
            r"[a-zA-Z\u4e00-\u9fff]{2,}",
            text.lower(),
        )
        freq: dict[str, int] = {}
        for word in words:
            freq[word] = freq.get(word, 0) + 1
        sorted_words = sorted(
            freq.items(),
            key=lambda x: x[1],
            reverse=True,
        )
        return [w for w, _ in sorted_words[:10]]

    async def retrieve(
        self,
        query: KnowledgeQuery,
    ) -> KnowledgeResult:
        """Retrieve wiki pages matching the query.

        Uses BM25 scoring over keyword and title tokens. Production
        should use embedding-based semantic search for better recall.

        Args:
            query (`KnowledgeQuery`):
                The retrieval query.

        Returns:
            `KnowledgeResult`: Matching chunks.
        """
        start = time.monotonic()

        if not self._initialized:
            await self.initialize()

        top_k = query.top_k or self.config.retrieval_top_k
        query_terms = re.findall(
            r"[a-zA-Z\u4e00-\u9fff]{2,}",
            query.query.lower(),
        )

        # Precompute document frequencies for BM25 IDF
        all_docs: list[dict[str, Any]] = []
        for chunk_id, entry in self._index.items():
            entry_keywords = entry.get("keywords", [])
            entry_title_words = re.findall(
                r"[a-zA-Z\u4e00-\u9fff]{2,}",
                entry.get("title", "").lower(),
            )
            doc_tokens = entry_keywords + entry_title_words
            all_docs.append(
                {
                    "chunk_id": chunk_id,
                    "entry": entry,
                    "tokens": doc_tokens,
                    "tf": {},
                },
            )

        N = len(all_docs)
        avgdl = sum(len(d["tokens"]) for d in all_docs) / N if N > 0 else 0
        # BM25 parameters
        k1 = 1.5
        b = 0.75

        # Compute IDF for each query term
        df: dict[str, int] = {}
        for term in set(query_terms):
            df[term] = sum(1 for d in all_docs if term in d["tokens"])

        scored: list[KnowledgeChunk] = []
        for doc in all_docs:
            # Compute term frequencies for this doc
            doc_tf: dict[str, int] = {}
            for token in doc["tokens"]:
                doc_tf[token] = doc_tf.get(token, 0) + 1

            # BM25 score
            bm25_score = 0.0
            dl = len(doc["tokens"])
            for term in query_terms:
                if term not in doc_tf:
                    continue
                tf = doc_tf[term]
                n = df.get(term, 0)
                idf = ((N - n + 0.5) / (n + 0.5) + 1) if n > 0 else 0
                tf_norm = (tf * (k1 + 1)) / (
                    tf + k1 * (1 - b + b * dl / max(avgdl, 1))
                )
                bm25_score += idf * tf_norm

            if bm25_score <= 0:
                continue

            entry = doc["entry"]
            chunk_id = doc["chunk_id"]
            entry_metadata = entry.get("metadata", {})
            wiki_path = os.path.join(
                self._compiled_dir_for(
                    entry_metadata.get("tenant_id", "default"),
                    entry_metadata.get("kb_id", "default"),
                ),
                entry.get("file", f"{chunk_id}.md"),
            )
            content = ""
            if os.path.exists(wiki_path):
                with open(wiki_path, "r", encoding="utf-8") as f:
                    content = f.read()

            metadata = dict(entry_metadata)
            metadata.setdefault("tenant_id", "default")
            metadata.setdefault("kb_id", "default")
            metadata["keywords"] = entry.get("keywords", [])

            chunk = KnowledgeChunk(
                chunk_id=chunk_id,
                source_id=entry.get("source_id", ""),
                title=entry.get("title", ""),
                content=content,
                score=bm25_score,
                metadata=metadata,
            )
            if not _chunk_in_scope(chunk, query):
                continue
            scored.append(chunk)

        scored.sort(key=lambda c: c.score, reverse=True)
        total = len(scored)
        scored = scored[:top_k]

        latency_ms = int((time.monotonic() - start) * 1000)

        # Audit the retrieve
        self._write_audit(
            "retrieve",
            query.tenant_id,
            query.kb_ids[0] if query.kb_ids else "default",
            query=query.query,
            results=total,
            latency_ms=latency_ms,
        )

        return KnowledgeResult(
            query=query.query,
            chunks=scored,
            total_found=total,
            latency_ms=latency_ms,
        )

    async def list_sources(
        self,
        tenant_id: str = "default",
    ) -> list[KnowledgeSource]:
        """List all raw sources for a specific tenant.

        Args:
            tenant_id (`str`):
                Tenant scope — only sources whose ``metadata.tenant_id``
                matches are returned.

        Returns:
            `list[KnowledgeSource]`: Tenant-scoped sources.
        """
        if not self._initialized:
            await self.initialize()

        sources: list[KnowledgeSource] = []
        if not os.path.exists(self.config.raw_dir):
            return sources

        # Collect candidate JSON files.  Under the flat layout they
        # live directly in raw_dir; under the scoped layout they live
        # under raw_dir/tenants/<tid>/kbs/<kid>/raw/*.json.
        source_paths: list[str] = []
        if self._scoped_layout_enabled():
            tenants_root = os.path.join(
                self.config.raw_dir,
                "tenants",
            )
            if os.path.isdir(tenants_root):
                for root, _dirs, files in os.walk(tenants_root):
                    if os.path.basename(root) != "raw":
                        continue
                    for filename in files:
                        if filename.endswith(".json"):
                            source_paths.append(
                                os.path.join(root, filename),
                            )
        else:
            for filename in os.listdir(self.config.raw_dir):
                if filename.endswith(".json"):
                    source_paths.append(
                        os.path.join(self.config.raw_dir, filename),
                    )

        for path in source_paths:
            with open(path, "r", encoding="utf-8") as f:
                data = json.load(f)
            # tenant_id is nested under "metadata" (see ingest).  The
            # previous implementation read it from the JSON top level
            # which always defaulted to "default", causing either
            # cross-tenant leakage or empty results.
            metadata = data.get("metadata", {}) or {}
            source_tenant = metadata.get("tenant_id", "default")
            if source_tenant != tenant_id:
                continue
            sources.append(
                KnowledgeSource(
                    source_id=data["source_id"],
                    title=data.get("title", ""),
                    content=data.get("content", ""),
                    source_type=data.get("source_type", "text"),
                    metadata=metadata,
                    created_at=data.get("created_at", ""),
                ),
            )
        return sources

    async def delete_source(self, source_id: str) -> bool:
        """Delete a source and its compiled pages.

        Args:
            source_id (`str`):
                The source to delete.

        Returns:
            `bool`: ``True`` if deleted.

        Raises:
            `ValueError`: If ``source_id`` contains path traversal
                characters (``..``, ``/``, ``os.sep``) or is an
                absolute path.
        """
        # Validate source_id to prevent path traversal. A valid
        # source_id is a bare filename stem — no path separators,
        # no parent-dir references, no absolute paths.
        if not source_id or not source_id.strip():
            raise ValueError("source_id must not be empty")
        if (
            ".." in source_id
            or "/" in source_id
            or os.sep in source_id
            or os.path.isabs(source_id)
        ):
            raise ValueError(
                f"Invalid source_id '{source_id}': contains path "
                "traversal characters or is an absolute path",
            )

        deleted = False

        raw_path = os.path.join(
            self.config.raw_dir,
            f"{source_id}.json",
        )
        if os.path.exists(raw_path):
            os.remove(raw_path)
            deleted = True

        to_remove = [
            chunk_id
            for chunk_id, entry in self._index.items()
            if entry.get("source_id") == source_id
        ]
        for chunk_id in to_remove:
            entry = self._index.pop(chunk_id)
            entry_metadata = entry.get("metadata", {})
            wiki_path = os.path.join(
                self._compiled_dir_for(
                    entry_metadata.get("tenant_id", "default"),
                    entry_metadata.get("kb_id", "default"),
                ),
                entry.get("file", f"{chunk_id}.md"),
            )
            if os.path.exists(wiki_path):
                os.remove(wiki_path)

        if to_remove:
            self._save_index()

        return deleted

    async def close(self) -> None:
        """Release resources."""
        self._initialized = False


def _register_default_adapter() -> None:
    """Register the LLM-Wiki adapter with the default factory.

    Called at module import time (see the ``_register_default_adapter()``
    invocation below) so that ``KnowledgeAdapterFactory.create()`` can
    instantiate the adapter without the caller needing to register it
    manually.
    """
    from ._adapter import get_default_factory

    factory = get_default_factory()

    @factory.register("llm_wiki")
    class _RegisteredLlmWikiAdapter(LlmWikiAdapter):
        pass


# Register the adapter with the default factory at import time.
# Previously this function was defined but never called, leaving the
# factory empty and causing KnowledgeAdapterFactory.create() to fail
# with "No knowledge adapter registered for backend 'llm_wiki'".
_register_default_adapter()
