# -*- coding: utf-8 -*-
"""Knowledge base base types and abstract contract.

Defines the core data models and the ``KnowledgeBaseBase`` ABC that
all knowledge backends must implement.

The design follows the LLM-Wiki "compiler pattern" (AOT retrieval):
- **Raw layer** — immutable source documents stored as-is.
- **Compiled layer** — pre-processed, structured knowledge pages
  generated by an LLM or pipeline, ready for retrieval.
- **Retrieval** — queries hit the compiled layer (fast), not the raw
  layer (slow). The compiled layer is maintained incrementally.

This contrasts with traditional RAG ("interpreter pattern") which
retrieves from raw documents on every query.
"""
from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from enum import Enum
from typing import Any


class KnowledgeBackend(str, Enum):
    """Supported knowledge base backend types."""

    LLM_WIKI = "llm_wiki"
    """LLM-Wiki compiler pattern (AOT). Reference:
    https://gist.github.com/rohitg00/2067ab416f7bbe447c1977edaaa681e2"""

    VECTOR_STORE = "vector_store"
    """Traditional vector store RAG (ChromaDB, FAISS, Pinecone, etc.)."""

    KNOWLEDGE_GRAPH = "knowledge_graph"
    """Knowledge graph backend (Neo4j, etc.)."""

    CUSTOM = "custom"
    """User-provided custom backend."""


@dataclass
class KnowledgeBaseConfig:
    """Configuration for a knowledge base instance.

    Args:
        backend (`str`):
            Backend type — see :class:`KnowledgeBackend`.
        raw_dir (`str`):
            Directory for raw source documents (immutable).
        compiled_dir (`str`):
            Directory for compiled/structured knowledge pages.
        embedding_model_config (`dict | None`):
            Embedding model configuration (provider, api_key, model,
            dimensions).  Reuses AS ``EmbeddingModelBase`` providers.
        llm_model_config (`dict | None`):
            LLM configuration for compilation/extraction steps.
        retrieval_top_k (`int`):
            Number of chunks to retrieve per query.
        retrieval_min_score (`float`):
            Minimum similarity score for inclusion in results.
        auto_compile (`bool`):
            Whether to auto-trigger compilation after ingestion.
        extra (`dict`):
            Backend-specific configuration (e.g. graph DB URL,
            collection name, wiki template).
    """

    backend: str = "llm_wiki"
    raw_dir: str = ""
    compiled_dir: str = ""
    embedding_model_config: dict[str, Any] | None = None
    llm_model_config: dict[str, Any] | None = None
    retrieval_top_k: int = 5
    retrieval_min_score: float = 0.0
    auto_compile: bool = False
    extra: dict[str, Any] = field(default_factory=dict)


@dataclass
class KnowledgeSource:
    """A raw source document in the knowledge base.

    Args:
        source_id (`str`):
            Unique identifier for this source.
        title (`str`):
            Human-readable title.
        content (`str`):
            Raw content text.
        source_type (`str`):
            Type of source — ``"text"``, ``"markdown"``,
            ``"pdf"``, ``"url"``, ``"code"``.
        metadata (`dict`):
            Extra metadata (author, tags, timestamps, etc.).
        created_at (`str`):
            ISO 8601 timestamp of ingestion.
    """

    source_id: str
    title: str
    content: str
    source_type: str = "text"
    metadata: dict[str, Any] = field(default_factory=dict)
    created_at: str = ""


@dataclass
class KnowledgeChunk:
    """A compiled/structured knowledge chunk.

    A chunk is the unit of retrieval — it's what gets returned when
    a query matches. In the LLM-Wiki pattern, a chunk is a structured
    wiki page section; in vector-store RAG, it's an embedded text
    fragment.

    Args:
        chunk_id (`str`):
            Unique identifier for this chunk.
        source_id (`str`):
            ID of the source this chunk was derived from.
        title (`str`):
            Chunk title (e.g. wiki page heading).
        content (`str`):
            Chunk content text.
        embedding (`list[float] | None`):
            Pre-computed embedding vector (if applicable).
        score (`float`):
            Retrieval relevance score (set during retrieval).
        metadata (`dict`):
            Extra metadata (tags, links, confidence, etc.).
    """

    chunk_id: str
    source_id: str
    title: str
    content: str
    embedding: list[float] | None = None
    score: float = 0.0
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass
class KnowledgeQuery:
    """A retrieval query against the knowledge base.

    Args:
        query (`str`):
            The natural-language query text.
        top_k (`int | None`):
            Override the config default for this query.
        min_score (`float | None`):
            Override the config minimum score.
        filter_metadata (`dict`):
            Metadata-based filter (e.g. ``{"source_type": "code"}``).
        tenant_id (`str`):
            Tenant scope for multi-tenant knowledge isolation.
    """

    query: str
    top_k: int | None = None
    min_score: float | None = None
    filter_metadata: dict[str, Any] = field(default_factory=dict)
    tenant_id: str = "default"


@dataclass
class KnowledgeResult:
    """Result of a knowledge retrieval operation.

    Args:
        query (`str`):
            The original query.
        chunks (`list[KnowledgeChunk]`):
            Retrieved chunks, ordered by relevance (highest first).
        total_found (`int`):
            Total matching chunks before applying ``top_k``.
        latency_ms (`int`):
            Retrieval latency in milliseconds.
    """

    query: str
    chunks: list[KnowledgeChunk] = field(default_factory=list)
    total_found: int = 0
    latency_ms: int = 0

    def to_context_text(self) -> str:
        """Format the result as a context string for LLM injection.

        Returns:
            `str`: Formatted context text.
        """
        if not self.chunks:
            return ""
        parts: list[str] = []
        for i, chunk in enumerate(self.chunks, 1):
            parts.append(f"[{i}] {chunk.title}\n{chunk.content}")
        return "\n\n".join(parts)


class KnowledgeBaseBase(ABC):
    """Abstract base class for knowledge base backends.

    Defines the contract for ingestion, compilation, and retrieval.
    Concrete backends (llm-wiki, vector store, knowledge graph)
    implement this interface.

    The lifecycle is:

    1. ``initialize()`` — set up connections, load indexes.
    2. ``ingest()`` — add raw source documents.
    3. ``compile()`` — process raw sources into structured chunks
       (LLM-Wiki AOT pattern; vector stores embed + index).
    4. ``retrieve()`` — query the compiled layer.
    5. ``close()`` — release resources.
    """

    def __init__(self, config: KnowledgeBaseConfig) -> None:
        """Initialize the base.

        Args:
            config (`KnowledgeBaseConfig`):
                The knowledge base configuration.
        """
        self.config = config
        self._initialized = False

    @property
    def is_initialized(self) -> bool:
        """Whether the backend has been initialized."""
        return self._initialized

    @abstractmethod
    async def initialize(self) -> None:
        """Provision resources (DB connections, index files, etc.)."""

    @abstractmethod
    async def ingest(
        self,
        source_id: str,
        content: str,
        title: str = "",
        source_type: str = "text",
        metadata: dict[str, Any] | None = None,
    ) -> KnowledgeSource:
        """Ingest a raw source document.

        The source is stored immutably in the raw layer. If
        ``config.auto_compile`` is true, compilation is triggered
        automatically after ingestion.

        Args:
            source_id (`str`):
                Unique identifier for the source.
            content (`str`):
                Raw content text.
            title (`str`):
                Human-readable title.
            source_type (`str`):
                Source type (text, markdown, pdf, url, code).
            metadata (`dict | None`):
                Extra metadata.

        Returns:
            `KnowledgeSource`: The stored source record.
        """

    @abstractmethod
    async def compile(self) -> int:
        """Compile raw sources into structured chunks.

        In the LLM-Wiki pattern, this uses an LLM to extract
        entities, summaries, and cross-references from raw documents
        and writes structured wiki pages.

        In the vector-store pattern, this chunks + embeds the raw
        documents and builds the vector index.

        Returns:
            `int`: Number of chunks produced.
        """

    @abstractmethod
    async def retrieve(
        self,
        query: KnowledgeQuery,
    ) -> KnowledgeResult:
        """Retrieve knowledge chunks matching a query.

        Operates against the compiled layer — raw sources are not
        searched directly.

        Args:
            query (`KnowledgeQuery`):
                The retrieval query.

        Returns:
            `KnowledgeResult`: Retrieved chunks and metadata.
        """

    @abstractmethod
    async def list_sources(
        self,
        tenant_id: str = "default",
    ) -> list[KnowledgeSource]:
        """List all ingested sources.

        Args:
            tenant_id (`str`):
                Tenant scope.

        Returns:
            `list[KnowledgeSource]`: All sources for the tenant.
        """

    @abstractmethod
    async def delete_source(self, source_id: str) -> bool:
        """Delete a source and its compiled chunks.

        Args:
            source_id (`str`):
                The source to delete.

        Returns:
            `bool`: ``True`` if deleted, ``False`` if not found.
        """

    async def close(self) -> None:
        """Release resources. Default is a no-op."""
        self._initialized = False
