# -*- coding: utf-8 -*-
"""LLM-Wiki adapter — compiler-pattern knowledge base.

Implements the LLM-Wiki architecture (AOT retrieval) as described
in https://gist.github.com/rohitg00/2067ab416f7bbe447c1977edaaa681e2

Three-layer model:

1. **Raw layer** (``raw_dir``) — immutable source documents stored
   as files. This is the "source of truth" — the trust root.
2. **Wiki/compiled layer** (``compiled_dir``) — structured Markdown
   wiki pages generated by an LLM compilation pass. Each page covers
   a concept/entity extracted from the raw sources, with
   cross-references and metadata. This is the retrieval target.
3. **Index** — a keyword/embedding index over the compiled pages
   for fast retrieval.

The compilation pipeline:

    Raw document → chunk → LLM extract entities/summaries
    → generate wiki pages → cross-link → write to compiled_dir
    → build index

Retrieval hits the compiled layer (not raw), so it's fast (ms-level
vs minute-level for full-text search).

This is a **skeleton implementation** — the LLM compilation step
and the embedding index are stubbed with simple keyword matching.
Production use requires wiring a real LLM and embedding model.
"""
from __future__ import annotations

import json
import os
import re
import time
from datetime import datetime
from typing import Any

from ._base import (
    KnowledgeChunk,
    KnowledgeQuery,
    KnowledgeResult,
    KnowledgeSource,
)
from ._adapter import KnowledgeAdapter
from ._registry import _chunk_in_scope


class LlmWikiAdapter(KnowledgeAdapter):
    """LLM-Wiki compiler-pattern knowledge base adapter.

    Stores raw sources as JSON files and compiled wiki pages as
    Markdown files. Uses simple keyword matching for retrieval
    (to be replaced with embedding-based search in production).

    Args:
        config (`KnowledgeBaseConfig`):
            Configuration with ``raw_dir`` and ``compiled_dir``
            paths set.
    """

    @classmethod
    def backend_name(cls) -> str:
        """Return the backend name.

        Returns:
            `str`: ``"llm_wiki"``
        """
        return "llm_wiki"

    async def initialize(self) -> None:
        """Create directories and load the index."""
        os.makedirs(self.config.raw_dir, exist_ok=True)
        os.makedirs(self.config.compiled_dir, exist_ok=True)
        self._index: dict[str, dict[str, Any]] = {}
        self._load_index()
        self._initialized = True

    def _load_index(self) -> None:
        """Load the compiled page index from disk."""
        index_path = os.path.join(
            self.config.compiled_dir,
            "_index.json",
        )
        if os.path.exists(index_path):
            with open(index_path, "r", encoding="utf-8") as f:
                self._index = json.load(f)

    def _save_index(self) -> None:
        """Persist the index to disk."""
        index_path = os.path.join(
            self.config.compiled_dir,
            "_index.json",
        )
        with open(index_path, "w", encoding="utf-8") as f:
            json.dump(self._index, f, ensure_ascii=False, indent=2)

    def _scoped_layout_enabled(self) -> bool:
        """Whether to use tenant/KB physical directories."""
        return bool(self.config.extra.get("scoped_layout"))

    def _kb_root(self, tenant_id: str, kb_id: str) -> str:
        """Return the physical root for a tenant/KB."""
        return os.path.join(
            self.config.raw_dir,
            "tenants",
            tenant_id,
            "kbs",
            kb_id,
        )

    def _raw_dir_for(self, tenant_id: str, kb_id: str) -> str:
        if not self._scoped_layout_enabled():
            return self.config.raw_dir
        return os.path.join(self._kb_root(tenant_id, kb_id), "raw")

    def _compiled_dir_for(self, tenant_id: str, kb_id: str) -> str:
        if not self._scoped_layout_enabled():
            return self.config.compiled_dir
        return os.path.join(self._kb_root(tenant_id, kb_id), "wiki")

    def _index_dir_for(self, tenant_id: str, kb_id: str) -> str:
        if not self._scoped_layout_enabled():
            return self.config.compiled_dir
        return os.path.join(self._kb_root(tenant_id, kb_id), "index")

    async def ingest(
        self,
        source_id: str,
        content: str,
        title: str = "",
        source_type: str = "text",
        metadata: dict[str, Any] | None = None,
    ) -> KnowledgeSource:
        """Store a raw source document as a JSON file.

        Args:
            source_id (`str`):
                Unique source identifier.
            content (`str`):
                Raw content.
            title (`str`):
                Source title.
            source_type (`str`):
                Source type.
            metadata (`dict | None`):
                Extra metadata.

        Returns:
            `KnowledgeSource`: The stored source record.
        """
        source_metadata = {
            "tenant_id": "default",
            "kb_id": "default",
        }
        source_metadata.update(metadata or {})
        source = KnowledgeSource(
            source_id=source_id,
            title=title or source_id,
            content=content,
            source_type=source_type,
            metadata=source_metadata,
            created_at=datetime.now().isoformat(),
        )

        raw_dir = self._raw_dir_for(
            source.metadata.get("tenant_id", "default"),
            source.metadata.get("kb_id", "default"),
        )
        os.makedirs(raw_dir, exist_ok=True)
        path = os.path.join(
            raw_dir,
            f"{source_id}.json",
        )
        with open(path, "w", encoding="utf-8") as f:
            json.dump(
                {
                    "source_id": source.source_id,
                    "title": source.title,
                    "content": source.content,
                    "source_type": source.source_type,
                    "metadata": source.metadata,
                    "created_at": source.created_at,
                },
                f,
                ensure_ascii=False,
                indent=2,
            )

        if self.config.auto_compile:
            await self.compile()

        return source

    async def compile(self) -> int:
        """Compile raw sources into structured wiki pages.

        For each raw source that hasn't been compiled yet:
        1. Split content into sections (by heading or paragraphs).
        2. Extract keywords (simple frequency-based; production
           should use LLM for entity extraction).
        3. Generate a wiki page per section as Markdown.
        4. Update the keyword index.

        Returns:
            `int`: Number of chunks (wiki pages) produced.
        """
        if not self._initialized:
            await self.initialize()

        compiled_ids = {
            entry.get("source_id") for entry in self._index.values()
        }

        chunk_count = 0
        source_paths: list[str] = []
        if self._scoped_layout_enabled():
            for root, _dirs, files in os.walk(self.config.raw_dir):
                if os.path.basename(root) != "raw":
                    continue
                for filename in files:
                    if filename.endswith(".json"):
                        source_paths.append(os.path.join(root, filename))
        else:
            for filename in os.listdir(self.config.raw_dir):
                if filename.endswith(".json"):
                    source_paths.append(
                        os.path.join(self.config.raw_dir, filename),
                    )

        for source_path in source_paths:
            with open(source_path, "r", encoding="utf-8") as f:
                source_data = json.load(f)

            source_id = source_data["source_id"]
            if source_id in compiled_ids:
                continue

            sections = self._split_sections(
                source_data["content"],
                source_data.get("title", source_id),
            )

            for i, (heading, body) in enumerate(sections):
                chunk_id = f"{source_id}__{i}"
                keywords = self._extract_keywords(body)

                metadata = source_data.get("metadata", {})
                compiled_dir = self._compiled_dir_for(
                    metadata.get("tenant_id", "default"),
                    metadata.get("kb_id", "default"),
                )
                os.makedirs(compiled_dir, exist_ok=True)
                wiki_path = os.path.join(
                    compiled_dir,
                    f"{chunk_id}.md",
                )
                wiki_content = (
                    f"# {heading}\n\n"
                    f"**Source**: {source_data.get('title', source_id)}\n"
                    f"**Section**: {i + 1}\n\n"
                    f"{body}\n"
                )
                with open(wiki_path, "w", encoding="utf-8") as f:
                    f.write(wiki_content)

                self._index[chunk_id] = {
                    "source_id": source_id,
                    "title": heading,
                    "keywords": keywords,
                    "file": f"{chunk_id}.md",
                    "metadata": source_data.get("metadata", {}),
                }
                chunk_count += 1

        self._save_index()
        if self._scoped_layout_enabled():
            for entry in self._index.values():
                metadata = entry.get("metadata", {})
                index_dir = self._index_dir_for(
                    metadata.get("tenant_id", "default"),
                    metadata.get("kb_id", "default"),
                )
                os.makedirs(index_dir, exist_ok=True)
                index_path = os.path.join(index_dir, "_index.json")
                scoped = {
                    cid: item for cid, item in self._index.items()
                    if item.get("metadata", {}).get("tenant_id", "default")
                    == metadata.get("tenant_id", "default")
                    and item.get("metadata", {}).get("kb_id", "default")
                    == metadata.get("kb_id", "default")
                }
                with open(index_path, "w", encoding="utf-8") as f:
                    json.dump(scoped, f, ensure_ascii=False, indent=2)
        return chunk_count

    def _split_sections(
        self,
        content: str,
        fallback_title: str,
    ) -> list[tuple[str, str]]:
        """Split content into (heading, body) sections.

        Splits by Markdown headings (``#``) or by double newlines
        as a fallback.

        Args:
            content (`str`):
                The content to split.
            fallback_title (`str`):
                Title for the first section if no heading found.

        Returns:
            `list[tuple[str, str]]`: (heading, body) pairs.
        """
        lines = content.split("\n")
        sections: list[tuple[str, str]] = []
        current_heading = fallback_title
        current_body: list[str] = []

        for line in lines:
            if line.strip().startswith("#"):
                if current_body:
                    sections.append(
                        (
                            current_heading,
                            "\n".join(current_body).strip(),
                        ),
                    )
                current_heading = line.strip().lstrip("#").strip()
                current_body = []
            else:
                current_body.append(line)

        if current_body:
            body = "\n".join(current_body).strip()
            if body:
                sections.append((current_heading, body))

        if not sections:
            sections.append((fallback_title, content))

        return sections

    def _extract_keywords(self, text: str) -> list[str]:
        """Extract keywords from text (simple frequency-based).

        Production should use LLM-based entity extraction or
        a proper NLP library.

        Args:
            text (`str`):
                The text to extract keywords from.

        Returns:
            `list[str]`: Top keywords.
        """
        words = re.findall(
            r"[a-zA-Z\u4e00-\u9fff]{2,}",
            text.lower(),
        )
        freq: dict[str, int] = {}
        for word in words:
            freq[word] = freq.get(word, 0) + 1
        sorted_words = sorted(
            freq.items(),
            key=lambda x: x[1],
            reverse=True,
        )
        return [w for w, _ in sorted_words[:10]]

    async def retrieve(
        self,
        query: KnowledgeQuery,
    ) -> KnowledgeResult:
        """Retrieve wiki pages matching the query.

        Uses simple keyword overlap scoring. Production should use
        embedding-based semantic search.

        Args:
            query (`KnowledgeQuery`):
                The retrieval query.

        Returns:
            `KnowledgeResult`: Matching chunks.
        """
        start = time.monotonic()

        if not self._initialized:
            await self.initialize()

        top_k = query.top_k or self.config.retrieval_top_k
        query_words = set(
            re.findall(
                r"[a-zA-Z\u4e00-\u9fff]{2,}",
                query.query.lower(),
            )
        )

        scored: list[KnowledgeChunk] = []
        for chunk_id, entry in self._index.items():
            entry_keywords = set(entry.get("keywords", []))
            entry_title_words = set(
                re.findall(
                    r"[a-zA-Z\u4e00-\u9fff]{2,}",
                    entry.get("title", "").lower(),
                )
            )
            overlap = len(
                query_words & (entry_keywords | entry_title_words),
            )
            if overlap == 0:
                continue

            score = overlap / max(len(query_words), 1)

            entry_metadata = entry.get("metadata", {})
            wiki_path = os.path.join(
                self._compiled_dir_for(
                    entry_metadata.get("tenant_id", "default"),
                    entry_metadata.get("kb_id", "default"),
                ),
                entry.get("file", f"{chunk_id}.md"),
            )
            content = ""
            if os.path.exists(wiki_path):
                with open(wiki_path, "r", encoding="utf-8") as f:
                    content = f.read()

            metadata = dict(entry.get("metadata", {}))
            metadata.setdefault("tenant_id", "default")
            metadata.setdefault("kb_id", "default")
            metadata["keywords"] = entry.get("keywords", [])

            chunk = KnowledgeChunk(
                chunk_id=chunk_id,
                source_id=entry.get("source_id", ""),
                title=entry.get("title", ""),
                content=content,
                score=score,
                metadata=metadata,
            )
            if not _chunk_in_scope(chunk, query):
                continue
            scored.append(chunk)

        scored.sort(key=lambda c: c.score, reverse=True)
        total = len(scored)
        scored = scored[:top_k]

        latency_ms = int((time.monotonic() - start) * 1000)

        return KnowledgeResult(
            query=query.query,
            chunks=scored,
            total_found=total,
            latency_ms=latency_ms,
        )

    async def list_sources(
        self,
        tenant_id: str = "default",
    ) -> list[KnowledgeSource]:
        """List all raw sources.

        Args:
            tenant_id (`str`):
                Tenant scope (currently ignored — all sources
                returned).

        Returns:
            `list[KnowledgeSource]`: All sources.
        """
        if not self._initialized:
            await self.initialize()

        sources: list[KnowledgeSource] = []
        if not os.path.exists(self.config.raw_dir):
            return sources

        for filename in os.listdir(self.config.raw_dir):
            if not filename.endswith(".json"):
                continue
            path = os.path.join(self.config.raw_dir, filename)
            with open(path, "r", encoding="utf-8") as f:
                data = json.load(f)
            sources.append(
                KnowledgeSource(
                    source_id=data["source_id"],
                    title=data.get("title", ""),
                    content=data.get("content", ""),
                    source_type=data.get("source_type", "text"),
                    metadata=data.get("metadata", {}),
                    created_at=data.get("created_at", ""),
                ),
            )
        return sources

    async def delete_source(self, source_id: str) -> bool:
        """Delete a source and its compiled pages.

        Args:
            source_id (`str`):
                The source to delete.

        Returns:
            `bool`: ``True`` if deleted.
        """
        deleted = False

        raw_path = os.path.join(
            self.config.raw_dir,
            f"{source_id}.json",
        )
        if os.path.exists(raw_path):
            os.remove(raw_path)
            deleted = True

        to_remove = [
            chunk_id
            for chunk_id, entry in self._index.items()
            if entry.get("source_id") == source_id
        ]
        for chunk_id in to_remove:
            entry = self._index.pop(chunk_id)
            entry_metadata = entry.get("metadata", {})
            wiki_path = os.path.join(
                self._compiled_dir_for(
                    entry_metadata.get("tenant_id", "default"),
                    entry_metadata.get("kb_id", "default"),
                ),
                entry.get("file", f"{chunk_id}.md"),
            )
            if os.path.exists(wiki_path):
                os.remove(wiki_path)

        if to_remove:
            self._save_index()

        return deleted

    async def close(self) -> None:
        """Release resources."""
        self._initialized = False


def _register_default_adapter() -> None:
    """Register the LLM-Wiki adapter with the default factory."""
    from ._adapter import get_default_factory

    factory = get_default_factory()

    @factory.register("llm_wiki")
    class _RegisteredLlmWikiAdapter(LlmWikiAdapter):
        pass
