name: Pre-commit

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        pip install -e ".[xruntime-dev]" pre-commit
    - name: Pre-commit starts
      run: |
        pre-commit install
        pre-commit run --all-files || true
        cat pre-commit.log 2>/dev/null || true
